#pragma once
class err
{
public:

	enum err_codes
	{
		OK,
		ERROR = -1,
		ERR_GETTING_PORT_SETTINGS = -2,
		ERR_SETTING_BAUDRATE = -3,
		ERR_FLUSHING = -4,
		ERR_SETTINGS_SERIAL_PORT_CONFIGURATION = -5,
		ERR_SETTING_EXCLUSIVE_ACCESS = -6,
		ERR_OPENING_SERIAL_PORT = -7,
		ERR_SETTING_THREAD_STACK_SIZE = -8,
		ERR_CREATING_SERIAL_PORT_READ_THREAD = -9,
		ERR_CREATING_SERIAL_PORT_WRITE_THREAD = -10,
		ERR_ALOCATING_MEMORY_FOR_RX_SERIAL_BUFFER = -11,
		ERR_ALOCATING_MEMORY_FOR_TX_SERIAL_BUFFER = -12,
		ERR_GPS_TIMEOUT = -13,
		ERR_GPS_LINE_OVERFLOW = -14,
		ERR_INVALID_PARAMETER = -15,
		ERR_INVALID_CHECKSUM = -16,
		ERR_EMPTY_FRAME = -17,
		ERR_OPEN = -18,
		ERR_READ_ERROR = -19,
		ERR_READ_TIMEOUT = -20,
		ERR_CHECKSUM_ERROR = -21,
		ERR_INVALID_FRAME = -22,
		ERR_NAVIGATOR_OPENING_FILE = -23,
		ERR_NAVIGATOR_INVALID_FILE_FORMAT = -24,		
		ERR_OPENING_CAMERA = -25,
		ERR_OPENING_NAVIGATION_VISUAL = -26,
		ERR_OPENING_NAVIGATION_LINE = -27,
		ERR_OPENING_HEAD = -28,
		ERR_NOT_FOUND = -29,
		NAVIGATOR_DONE = -99
	};
};